version: '3'
services:
  server:
    image: clojure:lein-alpine
    container_name: server
    working_dir: /root
    command: lein run
    ports:
      - 3000:3000
      - 38001:38001
    volumes:
      - .:/root
    depends_on:
      - docker_db
    networks:
      default:
        aliases:
          - kitsune.devel

  docker_db:
    image: postgres:alpine
    container_name: docker_db
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kitsune
      POSTGRES_db: kitsune
      POSTGRES_PASSWORD: whatever
    ports:
      - 5432
