version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein
        environment:
          DB__HOST: 127.0.0.1
      - image: postgres:alpine
        environment:
          POSTGRES_USER: kitsune
          POSTGRES_PASSWORD: whatever
    working_directory: ~/kitsune
    environment:
      LEIN_ROOT: true
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - lein-dependencies-{{ checksum "project.clj" }}
          - lein-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - .m2
          key: lein-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Install Postgres client
          command: sudo apt update && sudo apt install postgresql
      - run:
          name: Install required Postgres extensions
          command: echo "create extension hstore; create extension pgcrypto" | psql -U kitsune -h 127.0.0.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Migrate DB
          command: lein run migrate
      - run: lein test
  lint:
    docker:
      - image: clojure:lein
    working_directory: ~/kitsune
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - dependencies-{{ checksum "project.clj" }}
          - dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "project.clj" }}
      - run: lein eastwood
  deploy:
    docker:
      - image: clojure:lein
    environment:
      DEPLOY_HOST: 68.183.233.111
      PROD_CONFIG: config.edn
      KITSUNE_FOLDER: /usr/local/kitsune/
    working_directory: ~/kitsune
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - dependencies-{{ checksum "project.clj" }}
          - dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "project.clj" }}
      - run:
          name: "Compile jar"
          command: lein uberjar
      - run:
          name: Fix host authenticity
          command: |
            ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints: ["65:66:d8:7e:1e:69:ed:f9:62:5a:c1:f3:60:0a:0e:7c"]
      - run:
          name: "Copy jar to server"
          command: scp target/uberjar/kitsune.jar circleci@$DEPLOY_HOST:$KITSUNE_FOLDER
      - run:
          name: "Finally start the server"
          command: ssh circleci@$DEPLOY_HOST "cd $KITSUNE_FOLDER; pkill -2 java; sleep 2; java -Dconf=$PROD_CONFIG -jar kitsune.jar"
          background: true
      - run:
          name: "Keep connection open long enough to start the server"
          command: sleep 30

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - lint
      - deploy:
          requires:
            - test
            - lint
        #  filters:
        #    branches:
        #      only: develop
